# Generated by Django 5.2.5 on 2025-08-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
